// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7rQFVieFpnbS-t8mEf71-wm2yBYSMXQ',
    appId: '1:239087042530:web:cdaf0d1cfed0d5ac6203bb',
    messagingSenderId: '239087042530',
    projectId: 'legacy-6f966',
    authDomain: 'legacy-6f966.firebaseapp.com',
    storageBucket: 'legacy-6f966.firebasestorage.app',
    measurementId: 'G-2LW5RWZCZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHp5f9I9hKdb6LSizCf-I0aSl6Nd_4XjU',
    appId: '1:239087042530:android:d4de5e6ca2eb3efa6203bb',
    messagingSenderId: '239087042530',
    projectId: 'legacy-6f966',
    storageBucket: 'legacy-6f966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLGDk0zXOE8E60Fof9WX0iBMepd6Uopbg',
    appId: '1:239087042530:ios:b2de5e61579130526203bb',
    messagingSenderId: '239087042530',
    projectId: 'legacy-6f966',
    storageBucket: 'legacy-6f966.firebasestorage.app',
    iosBundleId: 'com.example.legacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLGDk0zXOE8E60Fof9WX0iBMepd6Uopbg',
    appId: '1:239087042530:ios:b2de5e61579130526203bb',
    messagingSenderId: '239087042530',
    projectId: 'legacy-6f966',
    storageBucket: 'legacy-6f966.firebasestorage.app',
    iosBundleId: 'com.example.legacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN7rQFVieFpnbS-t8mEf71-wm2yBYSMXQ',
    appId: '1:239087042530:web:c144a940104fd2266203bb',
    messagingSenderId: '239087042530',
    projectId: 'legacy-6f966',
    authDomain: 'legacy-6f966.firebaseapp.com',
    storageBucket: 'legacy-6f966.firebasestorage.app',
    measurementId: 'G-6B2SK6T9BX',
  );
}
